[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_MOCK_AUTH = "true"
  NEXT_PUBLIC_API_URL = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_MOCK_AUTH = "true"
  NODE_ENV = "production"
